include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - packages/**
    - lib/generated/**
    - lib/**.g.dart
    - lib/**.freezed.dart
    - android/**
    - ios/**

  errors:
    unused_import: ignore
    unused_local_variable: ignore
    unused_field: ignore
    unused_element: ignore
    dead_code: ignore
    unnecessary_import: ignore
    unnecessary_this: ignore
    unnecessary_const: ignore
    unnecessary_new: ignore
    prefer_const_constructors: ignore
    prefer_final_fields: ignore
    prefer_typing_uninitialized_variables: ignore
  enable-experiment:
    - dot-shorthands


linter:
  rules:
    # === Style ===
    prefer_single_quotes: true         # Enforce single quotes for strings
    always_use_package_imports: true   # Prevent relative imports across lib/
    require_trailing_commas: true      # Force trailing commas for nicer Flutter formatting
    prefer_const_constructors: true    # Use `const` when possible
    prefer_const_literals_to_create_immutables: true

    # === Safety ===
    avoid_dynamic_calls: true
    avoid_print: true                  # Use logging instead of print
    avoid_unnecessary_containers: true
    use_key_in_widget_constructors: true
    sized_box_for_whitespace: true     # Use SizedBox instead of Container for spacing
    prefer_final_fields: true          # Use `final` for fields where possible
    prefer_final_locals: true          # Use `final` for local vars

    # === Readability ===
    unnecessary_string_interpolations: true
    avoid_redundant_argument_values: true
    prefer_interpolation_to_compose_strings: true

    # === Maintainability ===
    depend_on_referenced_packages: true
    unnecessary_lambdas: true
    use_super_parameters: true         # Cleaner constructors with Dart 2.17+
    avoid_init_to_null: true

formatter:
  trailing_commas: preserve